import { ApolloWrapper } from '@/lib/Apollo/Apollo';
import './globals.css';
import StyledComponentsRegistry from '@/lib/StyledComponents/register';
import { Onest } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const onest = Onest({
  subsets: ['latin', 'cyrillic'],
  display: 'swap'
});
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ru' className={onest.className}>
      <body>
        <StyledComponentsRegistry>
          <ApolloWrapper>{children}</ApolloWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
